### PR TITLE
Arbitrary writer + Fix #15

### LINKED ISSUE #15: Panic on small terminal
### Issue
Progress bar panics when the message passed to `message(&str)` is too large to be displayed in the current terminal
### Code
```
extern crate pbr;

use pbr::ProgressBar;

fn main() {
    let mut pb = ProgressBar::new(1);
    pb.message(&format!("{:300}",""));// 300 chars of padding
    pb.tick();
}

```
### Panic
```
$ echo $COLUMNS
208
$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/simple`
thread 'main' panicked at 'attempted to subtract with overflow', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pbr-0.2.1/src/pb.rs:296
stack backtrace:
   1:     0x564487f957b4 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x564487f97c7b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x564487f978ff - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x564487f8f86e - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x564487f97f11 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x564487f901aa - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x564487f97ea1 - rust_begin_unwind
   8:     0x564487fcd3ff - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x564487fcd6d8 - core::panicking::panic::hd4053e15e2373559
  10:     0x564487f897af - pbr::pb::ProgressBar::draw::hd3bda774ee48668f
                        at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pbr-0.2.1/src/pb.rs:296
  11:     0x564487f86077 - pbr::pb::ProgressBar::tick::h90f6a1e14ec41113
                        at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pbr-0.2.1/src/pb.rs:213
  12:     0x564487f7d5c0 - simple::main::h8834ccd5a1286944
                        at src/main.rs:8
  13:     0x564487f97538 - std::panicking::try::call::hd0906b54b9bfbb20
  14:     0x564487fa160b - __rust_try
  15:     0x564487fa15ae - __rust_maybe_catch_panic
  16:     0x564487f96f6c - std::rt::lang_start::hfe4efe1fc39e4a30
  17:     0x564487f7dfd9 - main
  18:     0x7f11ab15c740 - __libc_start_main
  19:     0x564487f7d2b8 - _start
  20:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/simple` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by ernestrc**
- Added support for passing an arbitrary `Write` object instead of stdout. I think It makes it more testable and I don't see why it shouldn't be possible. I needed to print to stderr, for example.
- Fixes #15
- Exposed `total` field

I need it to happen for a project of mine. I understand it might not be exactly what you want so I'm open to discussing changes or removing the PR.

### CODE REVIEW

**Comment by ernestrc** [comment]
it's backwards compatible now

**Comment by a8m** [comment]
Awesome @ernestrc 
I'll try to look at it this weekend. thanks

File: src/pb.rs [hunk 1]
```diff
@@ -42,11 +43,10 @@ pub enum Units {
     Bytes,
 }
 
-#[derive(Debug)]
-pub struct ProgressBar {
+pub struct ProgressBar<T: Write> {
     start_time: SteadyTime,
     units: Units,
-    total: u64,
+    pub total: u64,
```
Comment (a8m) [inline src/pb.rs]: Can you please explain the reason behind it @ernestrc ? thanks

Comment (ernestrc) [inline src/pb.rs]: For certain tasks, specially those that are parallelized, the total is not known when instantiating the bar. 

Take for example a script that walks a directory structure and does an asynchronous operation on every file that it finds. This allows a client to update the total number of bytes to be processed as it discovers new files.

I think it should be exposed as a method, which would help with backwards compatibility if in the future we need do something else when the client updates the total. WDYT?

Comment (a8m) [inline src/pb.rs]: > Take for example a script that walks a directory structure and does an asynchronous operation on every file that it finds. This allows a client to update the total number of bytes/files/lines to be processed as it discovers new files.

Sounds fair. thanks.
